# Generated by Django 4.2.21 on 2025-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PipelineState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraping_in_progress', models.BooleanField(default=False)),
                ('scraping_completed_urls', models.JSONField(default=list)),
                ('scraping_failed_urls', models.JSONField(default=list)),
                ('scraping_total_urls', models.IntegerField(default=0)),
                ('scraping_current_year', models.CharField(blank=True, max_length=10, null=True)),
                ('ocr_in_progress', models.BooleanField(default=False)),
                ('ocr_completed_files', models.JSONField(default=list)),
                ('ocr_failed_files', models.JSONField(default=list)),
                ('ocr_total_files', models.IntegerField(default=0)),
                ('ocr_current_file', models.CharField(blank=True, max_length=255, null=True)),
                ('chunking_in_progress', models.BooleanField(default=False)),
                ('chunking_completed_files', models.JSONField(default=list)),
                ('chunking_failed_files', models.JSONField(default=list)),
                ('chunking_total_files', models.IntegerField(default=0)),
                ('chunking_current_file', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_in_progress', models.BooleanField(default=False)),
                ('embedding_completed_chunks', models.IntegerField(default=0)),
                ('embedding_total_chunks', models.IntegerField(default=0)),
                ('model_loaded', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
